image: depau/openscad:latest

stages:
  - deploy

render:
  stage: deploy
  script:
  - sed -i 's/^fn=.*;$/fn=500;/g' include/sizes.scad
  - make -j4 SCADC_FLAGS='-Dbuild_supports="none"' OUTDIR="no-supports" directories case case-ikea pogopin &
  - make -j4 SCADC_FLAGS='-Dbuild_supports="easy"' OUTDIR="supports-easy" directories case case-ikea &
  - make -j4 SCADC_FLAGS='-Dbuild_supports="hardcore"' OUTDIR="supports-hardcore" directories case case-ikea &
  - wait
  artifacts:
    paths:
    - no-supports
    - supports-easy
    - supports-hardcore
  only:
  - master
