image: archlinux

stages:
  - deploy

before_script:
  - pacman -Syu --noconfirm openscad make 

render:
  stage: deploy
  script:
  - sed -i 's/^fn=.*;$/fn=500;/g' include/sizes.scad
  - make -j3 directories case case-ikea pogopin
  artifacts:
    paths:
    - stl
  only:
  - master
